"""Add diagnostic centre operating hours

Revision ID: 790c5f24be98
Revises: 978e203cf6e0
Create Date: 2026-10-01 14:45:14.618371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790c5f24be98'
down_revision: Union[str, Sequence[str], None] = '978e203cf6e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "diagnostic_centres",
        sa.Column(
            "opening_time",
            sa.Time(),
            nullable=False,
            server_default=sa.text("'09:00:00'"),
        ),
    )

    op.add_column(
        "diagnostic_centres",
        sa.Column(
            "closing_time",
            sa.Time(),
            nullable=False,
            server_default=sa.text("'18:00:00'"),
        ),
    )

    op.alter_column(
        "diagnostic_centres",
        "opening_time",
        server_default=None,
    )

    op.alter_column(
        "diagnostic_centres",
        "closing_time",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnostic_centres', 'closing_time')
    op.drop_column('diagnostic_centres', 'opening_time')
    # ### end Alembic commands ###
